#!/bin/sh

if [ -x "/etc/init.d/osso-applet-notificationlight" ]; then
	        update-rc.d osso-applet-notificationlight start 20 2 5 . >/dev/null || exit $?
fi

echo  updating schemas

OSSO_PRODUCT_HARDWARE='RX-34'

[ -x /usr/bin/osso-product-info ] && eval `/usr/bin/osso-product-info`

case "$OSSO_PRODUCT_HARDWARE" in
        RX-34)
                cp /usr/share/osso-applet-notificationlight/RX-34.schemas /etc/gconf/schemas/osso-applet-notificationlight.schemas
                ;;
        RX-44)
                cp /usr/share/osso-applet-notificationlight/RX-44.schemas /etc/gconf/schemas/osso-applet-notificationlight.schemas
                ;;
	*)
                cp /usr/share/osso-applet-notificationlight/RX-51.schemas /etc/gconf/schemas/osso-applet-notificationlight.schemas
                ;;
	
esac

GCONF_CONFIG_SOURCE="xml:merged:/etc/gconf/gconf.xml.defaults" gconftool-2 --makefile-install-rule /etc/gconf/schemas/osso-applet-notificationlight.schemas >&1 > /dev/null
